//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appCine.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class pelicula
    {
        public int Id { get; set; }
        public string nombre { get; set; }
        public string genero { get; set; }
        public string duracion { get; set; }
        public string director { get; set; }

        [MaxLength(500)]
        public string sinopsis { get; set; }
        public Nullable<System.DateTime> lanzamiento { get; set; }
        public string categoria { get; set; }
        public string imagen { get; set; }
    }
}
